DROP DATABASE if EXISTS HEROES;
CREATE DATABASE HEROES;
USE HEROES;

CREATE TABLE HERO (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50),
  ALIAS VARCHAR(50),
  SUPERPOWER VARCHAR(50),
  WEAKNESS VARCHAR(50),
  CONSTRAINT HERO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE IMAGE (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50),
  IMAGE_TYPE VARCHAR(50),
  PIC_BYTE BLOB,
  HERO_ID INT NOT NULL,
  CONSTRAINT IMAGE_ID_PK PRIMARY KEY (ID),
  CONSTRAINT HERO_IMAGE_ID_FK FOREIGN KEY (HERO_ID) REFERENCES HERO(ID)
);

INSERT INTO HERO (ID, NAME, ALIAS, SUPERPOWER, WEAKNESS) VALUES (1001, 'Wolverine', 'James Logan Howlett', 'Steel Bones', 'None');
